### ISSUE TITLE
RuntimeError: The size of tensor a (370) must match the size of tensor b (170) at non-singleton dimension 1邻接矩阵数据和处理后的数据貌似不匹配

### ISSUE THREAD

**Issue by ZHUGUODONG1** [guokan987/DGCN#6]
Traceback (most recent call last):
  File "/home/zgd21/traffic/DGCN-master/GRCN.py", line 176, in <module>
    compute_val_loss(net, val_loader, loss_function, supports, device, epoch=0)
  File "/home/zgd21/traffic/DGCN-master/lib/utils.py", line 222, in compute_val_loss
    output,_,_ = net(val_w, val_d, val_r, supports)
  File "/opt/anaconda3/envs/zgd21tiankeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zgd21/traffic/DGCN-master/model.py", line 369, in forward
    x=self.block1(x,supports)
  File "/opt/anaconda3/envs/zgd21tiankeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zgd21/traffic/DGCN-master/utils.py", line 734, in forward
    fea1=self.gcn_conv(tem1,supports)
  File "/opt/anaconda3/envs/zgd21tiankeng/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zgd21/traffic/DGCN-master/utils.py", line 700, in forward
    L2 = 2 *torch.matmul( adj, L1) - L0
RuntimeError: The size of tensor a (370) must match the size of tensor b (170) at non-singleton dimension 1邻接矩阵数据和处理后的数据貌似不匹配

**Comment by ZHUGUODONG1** [comment]
parser.add_argument('--num_point', type=int, default=370, 
                    help='road Point Number [370/397] ', required=False) 是要把default=370换成170?

**Comment by ZHUGUODONG1** [comment]
370换成170这有代表着什么？

**Comment by guokan987** [comment]
路段节点数

**Comment by guokan987** [comment]
> 370换成170这有代表着什么？

路网的路段节点数量
